apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: www-example-com
spec:
  - prefix: /hr
    service: hr-portal
  
  - prefix: /finance
    service: [INSTANCE_NAME].c.[PROJECT_ID].internal