imports:
- path: network.py
- path: utils.py
- path: compute.py
- path: router.py
- path: firewall.py

resources:
- name: dev-env
  type: network.py 
  properties:
    subnets:
      - region: us-central1
        cidr: 10.0.0.0/16

- name: compute
  type: compute.py
  properties:
    network: dev-env
    region: us-central1
    zone: us-central1-a
    machineType: n1-standard-4
    tag: dev-tag
    os: ubuntu-os-cloud
    image: ubuntu-1804-bionic-v20200317

- name: router
  type: router.py
  properties:
    network: vpc
    region: us-central1

- name: firewall-rules
  type: firewall.py
  properties:
    network: vpc
    rules:
      - name: allow-iap-proxy
        sourceRanges:
          - 35.235.240.0/20
        targetTag: dev-tag
        allowed:
          - IPProtocol: tcp
            ports:
              - "22"
    